### ISSUE TITLE
Building shiboken with Python 3.5.0 on Mac OS El Capitan

### ISSUE THREAD

**Issue by MrLeeh** [PySide/shiboken-setup#3]
I just tried to build shiboken with the following steps on my Mac using Python 3.5.0. As it shows it didn' t work. I don' t know why subprocess.mswindows is called on a Mac, seems like a bug to me or am I doing something wrong?

```
$ git clone https://github.com/PySide/shiboken-setup.git shiboken-setup
$ cd shiboken-setup
$ python setup.py bdist_wheel --qmake=/usr/bin/qmake-qt4 --version=1.2.2

Traceback (most recent call last):
  File "setup.py", line 65, in <module>
    from utils import rmtree
  File "/Users/stefan/src/shiboken-setup/utils.py", line 10, in <module>
    import popenasync
  File "/Users/stefan/src/shiboken-setup/popenasync.py", line 26, in <module>
    if subprocess.mswindows:
AttributeError: module 'subprocess' has no attribute 'mswindows'
```

PS. If I switch to Python 3.4.3 (using pyenv) and trying to install I get a different error telling me that the git repository could not be downloaded:

```
$ python setup.py bdist_wheel --qmake=/usr/bin/qmake-qt4 --version=1.2.2
Initializing submodules for Shiboken version 1.2.2
Cloning into 'sources/shiboken'...
fatal: repository 'https://git.gitorious.org/pyside/shiboken.git/' not found
Clone of 'https://git.gitorious.org/pyside/shiboken.git' into submodule path 'sources/shiboken' failed
Traceback (most recent call last):
  File "setup.py", line 167, in <module>
    raise DistutilsSetupError("Failed to initialize the git submodules")
distutils.errors.DistutilsSetupError: Failed to initialize the git submodules
```
Am I missing something here?

**Comment by ctismer** [comment]
Shiboken was probably not updated after a big repository change.
PySide got updated, you can install that and use its shiboken.
But Python 3.5 seems still to be a problem: PySide is not ready for it, too.
